"""
Workflow tests for KeywordQueryEventListener (src.events.listeners).

This is the main entry point of the extension: every keystroke in Ulauncher
flows through on_event(). These tests exercise the full query workflow:

  - Save-mode detection ('ms new' sub-command)
  - Search mode: cache lookup → matching → sorting → rendering
  - Every error branch (config missing, bad DB, version mismatch...)
  - Smart Single Result filtering
  - Contextual learning integration points
"""

import pytest

import src.events.listeners as listeners_mod
from src.database.cache import SnippetCache
from src.events.listeners import KeywordQueryEventListener
from tests.helpers import (
    FakeKeywordQueryEvent,
    desc_of,
    items_of,
    make_extension,
    make_snippet,
)


@pytest.fixture(autouse=True)
def fresh_cache():
    """Isolate the module-level snippet cache per test."""
    SnippetCache.invalidate()
    yield
    SnippetCache.invalidate()


@pytest.fixture
def listener():
    return KeywordQueryEventListener()


# ===========================================================================
# Save-mode routing ('ms new')
# ===========================================================================


class TestSaveModeRouting:
    """Queries starting with 'new' must divert to save mode, not search."""

    @pytest.fixture(autouse=True)
    def spy_save_mode(self, monkeypatch):
        calls = []

        def fake_handle(self, query, extension):
            calls.append(query)
            return "SAVE_MODE_RESULT"

        monkeypatch.setattr(KeywordQueryEventListener, "_handle_save_mode", fake_handle)
        self.calls = calls

    def _run(self, listener, argument):
        return listener.on_event(FakeKeywordQueryEvent(argument), make_extension())

    def test_bare_new_routes_to_save(self, listener):
        assert self._run(listener, "new") == "SAVE_MODE_RESULT"

    def test_new_with_name_routes_to_save(self, listener):
        self._run(listener, "new my snippet name")

        assert self.calls == ["new my snippet name"]

    def test_case_insensitive(self, listener):
        self._run(listener, "NEW")

        assert len(self.calls) == 1

    def test_leading_whitespace_still_matches(self, listener):
        self._run(listener, "   new  ")

        assert len(self.calls) == 1

    def test_search_containing_new_elsewhere_not_diverted(self, listener, monkeypatch):
        # 'renewable energy' contains 'new' but doesn't start with it
        monkeypatch.setattr(
            SnippetCache,
            "get_snippets",
            classmethod(lambda cls, **kw: []),
        )
        result = self._run(listener, "renewable")

        assert result != "SAVE_MODE_RESULT"


class TestSaveModeExecution:
    """Behavior inside _handle_save_mode itself."""

    @pytest.fixture(autouse=True)
    def clipboard(self, monkeypatch):
        state = {"value": "clipboard payload", "raise": None}
        real_pyperclip = listeners_mod.pyperclip

        def fake_paste():
            if state["raise"] is not None:
                raise state["raise"]
            return state["value"]

        monkeypatch.setattr(real_pyperclip, "paste", fake_paste)
        return state

    def test_missing_db_path_shows_config_error(self, clipboard, listener):
        ext = make_extension(mc_db_path="")

        items = items_of(listener._handle_save_mode("new", ext))

        assert items[0].get_name() == "Configuration required"

    def test_preview_item_generated_with_clipboard_content(self, listener):
        ext = make_extension()
        from tests.helpers import custom_action_data

        item = items_of(listener._handle_save_mode("new my title", ext))[0]
        payload = custom_action_data(item._on_enter)

        assert item.get_name() == "Save as 'my title'"
        assert payload["content"] == "clipboard payload"
        assert payload["action"] == "save_snippet"

    def test_no_name_autogenerated_from_clipboard(self, listener):
        ext = make_extension()

        item = items_of(listener._handle_save_mode("new", ext))[0]

        assert item.get_name().startswith("Save as '")
        assert "clipboard payload" in item.get_name()

    def test_empty_clipboard_rejected(self, clipboard, listener):
        clipboard["value"] = "   \n\t"

        items = items_of(listener._handle_save_mode("new", make_extension()))

        assert items[0].get_name() == "Empty Clipboard"

    def test_pyperclip_exception_shows_install_hint(self, clipboard, listener):
        import pyperclip

        clipboard["raise"] = pyperclip.PyperclipException("no xclip")

        items = items_of(listener._handle_save_mode("new", make_extension()))

        assert items[0].get_name() == "Clipboard Error"
        assert "xclip" in desc_of(items[0])

    def test_unexpected_clipboard_error_handled(self, clipboard, listener):
        clipboard["raise"] = RuntimeError("weird window manager")

        items = items_of(listener._handle_save_mode("new", make_extension()))

        assert items[0].get_name() == "Clipboard Error"


# ===========================================================================
# Search mode — happy path
# ===========================================================================


class TestSearchHappyPath:
    """Standard query flow end-to-end through on_event."""

    @pytest.fixture(autouse=True)
    def seeded_cache(self, monkeypatch):
        snippets = [
            make_snippet(name="python script", content="print('x')"),
            make_snippet(name="git rebase", content="git rebase -i"),
        ]
        monkeypatch.setattr(
            SnippetCache,
            "get_snippets",
            classmethod(lambda cls, **kw: [dict(s) for s in snippets]),
        )

    def test_empty_query_lists_all_snippets(self, listener):
        items = items_of(listener.on_event(FakeKeywordQueryEvent(""), make_extension()))

        names = {i.get_name() for i in items}
        assert names == {"python script", "git rebase"}

    def test_matching_query_returns_relevant_first(self, listener):
        action = listener.on_event(FakeKeywordQueryEvent("python"), make_extension())

        assert len(items_of(action)) >= 1
        assert items_of(action)[0].get_name() == "python script"

    def test_history_recorded_on_selection_payload(self, listener):
        from tests.helpers import history_payload_of

        item = items_of(
            listener.on_event(FakeKeywordQueryEvent("python"), make_extension())
        )[0]
        payload = history_payload_of(item)

        assert payload["action"] == "record_history"
        assert payload["query"] == "python"
        assert payload["snippet_name"] == "python script"

    def test_no_results_message_when_nothing_matches(self, listener, monkeypatch):
        # A query that matches nothing above the fuzzy threshold
        action = listener.on_event(FakeKeywordQueryEvent("zzzzqqqq"), make_extension())

        items = items_of(action)
        assert len(items) == 1
        assert items[0].get_name() == "No results"


# ===========================================================================
# Search mode — configuration & database errors
# ===========================================================================


class TestSearchErrorBranches:
    """Every failure branch produces a distinct, actionable message."""

    def run_query(self, listener, ext, query="anything"):
        return items_of(listener.on_event(FakeKeywordQueryEvent(query), ext))

    @pytest.fixture(autouse=True)
    def empty_cache(self, monkeypatch):
        monkeypatch.setattr(
            SnippetCache, "get_snippets", classmethod(lambda cls, **kw: [])
        )

    def test_missing_db_path(self, listener):
        items = self.run_query(listener, make_extension(mc_db_path=""))

        assert items[0].get_name() == "Configuration required"

    def test_v5_file_instead_of_directory(self, listener, tmp_path):
        vault_file = tmp_path / "not-a-dir"
        vault_file.write_text("x")
        ext = make_extension(mc_db_path=str(vault_file), masscode_version="v5")

        items = self.run_query(listener, ext)

        assert items[0].get_name() == "Vault Path Error"
        assert "markdown-vault" in desc_of(items[0])

    def test_v5_directory_without_state_json(self, listener, tmp_path):
        bare = tmp_path / "bare-vault"
        bare.mkdir()
        ext = make_extension(mc_db_path=str(bare), masscode_version="v5")

        items = self.run_query(listener, ext)

        assert items[0].get_name() == "Invalid Vault"
        assert "state.json" in desc_of(items[0])

    def test_v5_generic_error_for_missing_path(self, listener):
        ext = make_extension(mc_db_path="/nonexistent/vault", masscode_version="v5")

        items = self.run_query(listener, ext)

        assert items[0].get_name() == "Markdown Vault Error"

    def test_v4_selected_but_json_file_detected(self, listener, tmp_path):
        json_file = tmp_path / "actually.json"
        json_file.write_text('{"snippets": []}')
        ext = make_extension(mc_db_path=str(json_file), masscode_version="v4")

        items = self.run_query(listener, ext)

        assert items[0].get_name() == "Version Mismatch Error"
        assert "V3 or earlier" in desc_of(items[0])

    def test_v3_selected_but_sqlite_file_detected(self, listener, tmp_path):
        sqlite_file = tmp_path / "actually.db"
        import sqlite3

        conn = sqlite3.connect(str(sqlite_file))
        conn.execute("CREATE TABLE t (x)")
        conn.commit()
        conn.close()
        ext = make_extension(mc_db_path=str(sqlite_file), masscode_version="v3")

        items = self.run_query(listener, ext)

        assert items[0].get_name() == "Version Mismatch Error"
        assert "V4+" in desc_of(items[0])

    def test_v4_default_error_when_path_missing(self, listener):
        ext = make_extension(mc_db_path="/ghost/massCode.db", masscode_version="v4")

        items = self.run_query(listener, ext)

        assert items[0].get_name() == "SQLite Database Error"

    def test_v3_default_error_when_path_missing(self, listener):
        ext = make_extension(mc_db_path="/ghost/db.json", masscode_version="v3")

        items = self.run_query(listener, ext)

        assert items[0].get_name() == "JSON Database Error"


# ===========================================================================
# Smart ratio preference parsing
# ===========================================================================


class TestSmartRatioParsing:
    """
    Invalid smart_single_result_ratio values disable the feature silently
    instead of crashing the whole query.
    """

    @pytest.fixture(autouse=True)
    def one_snippet(self, monkeypatch):
        monkeypatch.setattr(
            SnippetCache,
            "get_snippets",
            classmethod(lambda cls, **kw: [make_snippet(name="only one", content="c")]),
        )

    @pytest.mark.parametrize("ratio_value", ["abc", "", "1.5", "-0.2"])
    def test_invalid_ratios_do_not_crash(self, listener, ratio_value):
        ext = make_extension(smart_single_result_ratio=ratio_value)

        items = items_of(listener.on_event(FakeKeywordQueryEvent("only"), ext))

        # Query still completes normally with the feature disabled
        assert any("only one" in i.get_name() for i in items)

    def test_valid_boundary_one_accepted(self, listener):
        ext = make_extension(smart_single_result_ratio="1.0")

        items = items_of(listener.on_event(FakeKeywordQueryEvent("only"), ext))

        assert any("only one" in i.get_name() for i in items)


# ===========================================================================
# _apply_smart_single_result (unit-level)
# ===========================================================================


class TestApplySmartSingleResult:
    """Ratio-based reduction to a single result."""

    def test_dominant_snippet_collapses_to_single_result(self):
        history = {"q": {"alpha": 9, "beta": 1}}  # alpha ratio = 0.9

        result = listener_apply(history, "q", threshold=0.7)

        assert len(result) == 1
        assert result[0]["name"] == "alpha"

    def test_ratio_below_threshold_keeps_all(self):
        history = {"q": {"alpha": 5, "beta": 5}}  # alpha ratio = 0.5

        result = listener_apply(history, "q", threshold=0.7)

        assert len(result) == 2

    def test_unknown_query_history_requires_caller_guard(self):
        """
        QUIRK (pinned): _apply_smart_single_result indexes the history dict
        directly — it RAISES KeyError when the query has no history entry.
        Callers MUST pre-check `query in context_history` (on_event does).
        """
        with pytest.raises(KeyError):
            listener_apply({"other": {"x": 1}}, "q", threshold=0.1)

    def test_zero_total_selections_keeps_all(self):
        result = listener_apply({"q": {}}, "q", threshold=0.5)

        assert len(result) == 2

    def test_exact_threshold_boundary_passes(self):
        history = {"q": {"alpha": 1, "beta": 1}}  # alpha ratio = 0.5

        result = listener_apply(history, "q", threshold=0.5)

        assert len(result) == 1


def listener_apply(history, query, threshold):
    """Helper invoking _apply_smart_single_result with sensible matches."""
    listener = KeywordQueryEventListener()
    matches = [
        {"name": "alpha", "fuzzy_score": 90},
        {"name": "beta", "fuzzy_score": 80},
    ]
    return listener._apply_smart_single_result(
        matches=matches,
        query=query,
        context_history=history,
        smart_ratio_threshold=threshold,
    )


# ===========================================================================
# _match_snippets (unit-level)
# ===========================================================================


class TestMatchSnippets:
    """Snippet→match transformation with fragments and context scores."""

    def make_listener(self):
        return KeywordQueryEventListener()

    def test_threshold_filters_weak_matches(self):
        listener = self.make_listener()
        snippets = [make_snippet(name="target snippet", content="xyz")]

        matches = listener._match_snippets(snippets, "totally-unrelated-zzz", {}, False)

        assert matches == []

    def test_no_query_returns_everything(self):
        listener = self.make_listener()
        snippets = [make_snippet(name=f"s{i}") for i in range(5)]

        matches = listener._match_snippets(snippets, "", {}, False)

        assert len(matches) == 5
        assert all(m["fuzzy_score"] == 100 for m in matches)

    def test_fragment_display_names_and_labels(self):
        listener = self.make_listener()
        snippets = [
            {
                "name": "multi",
                "content": [
                    {"label": "Frag A", "value": "aaa"},
                    {"label": "Frag B", "value": "bbb"},
                ],
            }
        ]

        matches = listener._match_snippets(snippets, "", {}, False)

        assert {m["name"] for m in matches} == {"multi [Frag A]", "multi [Frag B]"}
        assert {m["fragment_label"] for m in matches} == {"Frag A", "Frag B"}

    def test_context_score_computed_from_relevant_contexts(self):
        listener = self.make_listener()
        snippets = [make_snippet(name="docker ps", content="docker ps -a")]
        contexts = {
            "dock": {
                "snippets": {"docker ps": 3},
                "relevance": 1.0,
            }
        }

        matches = listener._match_snippets(
            snippets, "dock", contexts, contextual_learning_enabled=True
        )

        scored = next(m for m in matches if m["name"] == "docker ps")
        assert scored["context_score"] == int(3 * 1.0 * 100)

    def test_context_ignored_when_learning_disabled(self):
        listener = self.make_listener()
        snippets = [make_snippet(name="docker ps", content="docker ps")]
        contexts = {"dock": {"snippets": {"docker ps": 3}, "relevance": 1.0}}

        matches = listener._match_snippets(
            snippets, "dock", contexts, contextual_learning_enabled=False
        )

        assert all(m["context_score"] == 0 for m in matches)

    def test_match_payload_keys_complete(self):
        listener = self.make_listener()
        snippets = [make_snippet(name="simple", content="code")]

        matches = listener._match_snippets(snippets, "sim", {}, False)

        expected_keys = {
            "name",
            "content",
            "fragment_label",
            "query",
            "fuzzy_score",
            "context_score",
        }
        assert set(matches[0]) == expected_keys


# ===========================================================================
# Exception safety
# ===========================================================================


class TestExceptionSafety:
    """Crashes inside the pipeline degrade into user-visible errors."""

    def test_nameerror_maps_to_library_error(self, listener, monkeypatch):
        monkeypatch.setattr(
            SnippetCache,
            "get_snippets",
            classmethod(lambda cls, **kw: [make_snippet(name="x", content="y")]),
        )

        def raise_name_error(*args, **kwargs):
            raise NameError("name 'fuzz' is not defined")

        monkeypatch.setattr(listeners_mod, "calculate_fuzzy_score", raise_name_error)

        items = items_of(
            listener.on_event(FakeKeywordQueryEvent("x"), make_extension())
        )

        assert items[0].get_name() == "Library Error"

    def test_generic_exception_maps_to_internal_error(self, listener, monkeypatch):
        def explode(cls, **kw):
            raise RuntimeError("cache exploded")

        monkeypatch.setattr(SnippetCache, "get_snippets", classmethod(explode))

        items = items_of(
            listener.on_event(FakeKeywordQueryEvent("x"), make_extension())
        )

        assert items[0].get_name() == "Internal Error"


# ===========================================================================
# Contextual learning integration within on_event
# ===========================================================================


class TestContextualLearningIntegration:
    """History loading feeds both boosting and smart-single-result."""

    def test_history_boosts_context_score_in_output(self, listener, monkeypatch):
        monkeypatch.setattr(
            SnippetCache,
            "get_snippets",
            classmethod(
                lambda cls, **kw: [
                    make_snippet(name="first choice", content="aaa"),
                    make_snippet(name="second choice", content="bbb"),
                ]
            ),
        )
        monkeypatch.setattr(
            listeners_mod,
            "load_context_history",
            lambda *a, **k: {"cho": {"second choice": 10}},
        )
        ext = make_extension(enable_contextual_learning="true")

        items = items_of(listener.on_event(FakeKeywordQueryEvent("cho"), ext))

        boosted = next(i for i in items if "second choice" in i.get_name())
        assert boosted.get_name().startswith("★")  # star marks learned picks

    def test_smart_single_result_triggers_end_to_end(self, listener, monkeypatch):
        monkeypatch.setattr(
            SnippetCache,
            "get_snippets",
            classmethod(
                lambda cls, **kw: [
                    make_snippet(name="winner", content="w"),
                    make_snippet(name="loser", content="l"),
                ]
            ),
        )
        monkeypatch.setattr(
            listeners_mod,
            "load_context_history",
            lambda *a, **k: {"winner": {"winner": 20, "loser": 1}},
        )
        ext = make_extension(
            enable_contextual_learning="true", smart_single_result_ratio="0.8"
        )

        items = items_of(listener.on_event(FakeKeywordQueryEvent("winner"), ext))

        assert len(items) == 1
        assert items[0].get_name() == "★ winner"

    def test_smart_disabled_by_ratio_zero(self, listener, monkeypatch):
        monkeypatch.setattr(
            SnippetCache,
            "get_snippets",
            classmethod(
                lambda cls, **kw: [
                    make_snippet(name="winner one", content="w"),
                    make_snippet(name="winner two", content="l"),
                ]
            ),
        )
        monkeypatch.setattr(
            listeners_mod,
            "load_context_history",
            lambda *a, **k: {"winner": {"winner one": 20, "winner two": 1}},
        )
        ext = make_extension(enable_contextual_learning="true")  # ratio default 0.0

        items = items_of(listener.on_event(FakeKeywordQueryEvent("winner"), ext))

        # Feature off (ratio=0.0) → both snippets stay listed, no collapse
        names = {i.get_name().lstrip("★ ") for i in items}
        assert {"winner one", "winner two"} <= names

    def test_smart_active_collapses_same_scenario(self, listener, monkeypatch):
        """Same data with ratio>threshold → exactly one result survives."""
        monkeypatch.setattr(
            SnippetCache,
            "get_snippets",
            classmethod(
                lambda cls, **kw: [
                    make_snippet(name="winner one", content="w"),
                    make_snippet(name="winner two", content="l"),
                ]
            ),
        )
        monkeypatch.setattr(
            listeners_mod,
            "load_context_history",
            lambda *a, **k: {"winner": {"winner one": 20, "winner two": 1}},
        )
        ext = make_extension(
            enable_contextual_learning="true", smart_single_result_ratio="0.8"
        )

        items = items_of(listener.on_event(FakeKeywordQueryEvent("winner"), ext))

        assert len(items) == 1
        assert "winner one" in items[0].get_name()

    def test_learning_off_skips_history_loading(self, listener, monkeypatch):
        load_calls = []
        monkeypatch.setattr(
            SnippetCache,
            "get_snippets",
            classmethod(lambda cls, **kw: [make_snippet(name="plain", content="p")]),
        )
        monkeypatch.setattr(
            listeners_mod,
            "load_context_history",
            lambda *a, **k: load_calls.append(1) or {},
        )
        ext = make_extension(enable_contextual_learning="false")

        listener.on_event(FakeKeywordQueryEvent("plain"), ext)

        assert load_calls == []
